name: nx-test-and-build
author: 'Peter Jokumsen'
description: 'Script to test and build project'

inputs:
  project-name:
    description: 'Project name to test and build'
    required: true

runs:
  using: 'composite'
  steps:
    - shell: pwsh
      run: npx nx run ${{ inputs.project-name }}:test --code-coverage
      name: Test ${{ inputs.project-name }}

    - shell: pwsh
      run: npx nx run ${{ inputs.project-name }}:build:production
      name: Build ${{ inputs.project-name }}
