on:
  push:
    branches: ['main']

name: CD

permissions: write-all

jobs:
  deploy:
    uses: chill-viking/workflows/.github/workflows/swa-deploy.yml@main
    name: SWA
    with:
      output_location: dist/apps/chill-viking-ng-libs
      always_deploy: true
    secrets:
      swa_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_FLOWER_0950BD703 }}
      git_token: ${{ secrets.GITHUB_TOKEN }}

  release-please:
    uses: ./.github/workflows/release-please.yml
    name: Release
    secrets:
      git_token: ${{ secrets.ORG_PAT }}
      sonar_token: ${{ secrets.ORG_SONAR_TOKEN }}

  publish-layout:
    uses: ./.github/workflows/npm-publish.yml
    needs: release-please
    name: Publish Alpha build
    if: >
      needs.release-please.outputs.releases_created == 'true'
      && contains(needs.release-please.outputs.paths_released, 'libs/layout')
    with:
      nx_project: layout
      project_path: libs/layout
      alpha_build: false
    secrets:
      npm_token: ${{ secrets.ORG_NPM_TOKEN }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
