name: publish-demo-app-coverage
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

env:
  SONAR_TOKEN: ${{ secrets.DEMO_APP_SONAR_TOKEN }}
  COVERAGE_LOCATION: 'coverage/lcov.info'
  CONFIG_LOCATION: 'tsconfig.app.json'
  NX_PROJECT: 'chill-viking-ng-libs'
  PROJECT_BASE: 'apps/chill-viking-ng-libs'

jobs:
  main:
    name: test, build, and publish
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: nrwl/nx-set-shas@v3

      - uses: ./actions/npm-ci-with-cache

      - uses: ./actions/nx-affected-test-and-build
        with:
          project-name: ${{ env.NX_PROJECT }}

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
        with:
          path: ${{ env.PROJECT_BASE }}

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: ${{ env.PROJECT_BASE }}
          args: >
            -Dsonar.javascript.lcov.reportPaths=${{ env.COVERAGE_LOCATION }}
            -Dsonar.typescript.tsconfigPaths=${{ env.CONFIG_LOCATION }}
            -Dsonar.projectVersion=${{ steps.package-version.outputs.current-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
