on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

name: chill-viking-ng-libs-sonar-cloud

permissions:
  contents: read

jobs:
  use-workflow:
    name: test, build, and publish
    uses: chill-viking/workflows/.github/workflows/nx-sonar-cloud-scan.yml@main
    with:
      sonar-project: chill-viking-org_ng-libs-demo-app
      project-location: apps/chill-viking-ng-libs
      project-name: chill-viking-ng-libs
      config-location: tsconfig.app.json
      package-location: ./apps/chill-viking-ng-libs
    secrets:
      sonar-token: ${{ secrets.DEMO_APP_SONAR_TOKEN }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
