on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, closed]
  merge_group:

name: CI

permissions:
  contents: read
  pull-requests: write

jobs:
  cache-deps:
    runs-on: ubuntu-latest
    name: Install Dependencies
    steps:
      - uses: actions/checkout@v3

      - uses: chill-viking/npm-ci@latest
        name: Install dependencies w/ caching

  nx-affected:
    uses: chill-viking/workflows/.github/workflows/nx-test-affected.yml@main
    name: Test affected
    if: github.event.action != 'closed'
    needs: cache-deps

  publish-to-sonar-cloud:
    uses: chill-viking/workflows/.github/workflows/nx-sonar-cloud-all.yml@main
    name: Coverage Report
    if: >
      github.event.action != 'closed'
      && github.event_name != 'push'
      && github.event_name != 'merge_group'
    needs: cache-deps
    secrets:
      sonar-token: ${{ secrets.ORG_SONAR_TOKEN }}
      github-token: ${{ secrets.GITHUB_TOKEN }}

  publish-alpha:
    uses: ./.github/workflows/npm-publish.yml
    name: Publish Layout Alpha build
    if: >
      github.event.action != 'closed'
      && github.event_name != 'push'
      && github.event_name != 'merge_group'
    needs: cache-deps
    with:
      nx_project: layout
      project_path: libs/layout
    secrets:
      npm_token: ${{ secrets.ORG_NPM_TOKEN }}
      git_token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    uses: chill-viking/workflows/.github/workflows/swa-deploy.yml@main
    name: SWA
    needs: cache-deps
    if: >
      always()
      && github.event_name != 'push'
      && github.event_name != 'merge_group'
    with:
      output_location: dist/apps/chill-viking-ng-libs
    secrets:
      swa_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_ASHY_FLOWER_0950BD703 }}
      git_token: ${{ secrets.GITHUB_TOKEN }}
