on:
  push:
    branches: [main]
    paths:
      - libs/layout/**
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
    paths:
      - libs/layout/**

name: layout-lib-sonar-cloud

permissions:
  contents: read

jobs:
  use-workflow:
    name: test, build, and publish
    uses: chill-viking/workflows/.github/workflows/nx-sonar-cloud-scan.yml@main
    with:
      sonar-project: chill-viking-org_ng-libs-cv-layout
      project-location: libs/layout
      project-name: layout
      config-location: tsconfig.lib.json
      package-location: ./libs/layout/
    secrets:
      sonar-token: ${{ secrets.LAYOUT_LIB_SONAR_TOKEN }}
      github-token: ${{ secrets.GITHUB_TOKEN }}
