on:
  push:
    branches: [main]
    paths:
      - libs/layout/**
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
    paths:
      - libs/layout/**

name: layout-lib-sonar-cloud

env:
  SONAR_TOKEN: ${{ secrets.LAYOUT_LIB_SONAR_TOKEN }}
  COVERAGE_LOCATION: 'coverage/lcov.info'
  CONFIG_LOCATION: 'tsconfig.lib.json'
  NX_PROJECT: 'layout'
  PROJECT_BASE: 'libs/layout'

jobs:
  main:
    name: test, build, and publish
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@v3
        name: 'Checkout code'

      - uses: ./actions/npm-ci-with-cache
        name: Install Dependencies

      - uses: ./actions/nx-test-and-build
        name: Test and Build project
        with:
          project-name: ${{ env.NX_PROJECT }}

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
        with:
          path: ${{ env.PROJECT_BASE }}

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          projectBaseDir: ${{ env.PROJECT_BASE }}
          args: >
            -Dsonar.javascript.lcov.reportPaths=${{ env.COVERAGE_LOCATION }}
            -Dsonar.typescript.tsconfigPaths=${{ env.CONFIG_LOCATION }}
            -Dsonar.projectVersion=${{ steps.package-version.outputs.current-version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ env.SONAR_TOKEN }}
