on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
    paths:
      - libs/layout/**

name: npm-publish-layout-alpha

permissions: read-all

env:
  NX_PROJECT: 'layout'
  PROJECT_PATH: 'libs/layout'

jobs:
  #  prepare-version:
  publish-lib:
    name: publish alpha @chill-viking/layout
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@v3
        name: 'Checkout code'

      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@main
        with:
          path: ${{ env.PROJECT_PATH }}

      - name: Bump major for alpha version
        id: bumped-version
        run: |
          a=${{ steps.package-version.outputs.current-version }}
          v=(${a//\./ })
          x=${v[0]}
          major=$(($x + 1))
          minor=${v[1]}
          patch=${v[2]}
          newVersion="$major.$minor.$patch"
          echo "version=${newVersion}" >> $GITHUB_OUTPUT

      - name: Create alpha version
        id: alpha-version
        run: |
          newVersion=${{ steps.bumped-version.outputs.version }}
          num=${{ github.run_number }}
          echo "version=${newVersion}-alpha.${num}" >> $GITHUB_OUTPUT

      - uses: ./actions/run-npm-publish
        name: Publish to NPM
        with:
          npm-auth-token: ${{ secrets.ORG_NPM_TOKEN }}
          project-name: ${{ env.NX_PROJECT }}
          project-location: ${{ env.PROJECT_PATH }}
          project-dist-location: dist/${{ env.PROJECT_PATH }}
          project-version: ${{ steps.alpha-version.outputs.version }}
          project-tag: 'alpha'
