on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

name: nx-cloud-affected-ci

permissions: read-all

jobs:
  output-context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  use-workflow:
    uses: chill-viking/workflows/.github/workflows/nx-test-affected.yml@main
    name: Test affected
