on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
    types: [opened, synchronize, reopened]

name: nx-cloud-affected-ci

permissions: read-all

jobs:
  use-workflow:
    uses: chill-viking/workflows/.github/workflows/nx-test-affected.yml@main
    name: Test affected
