on:
  push:
    branches: ['main']

name: release-please

permissions: write-all

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release.outputs.releases_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
      others: ${{ steps.release.outputs }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: google-github-actions/release-please-action@v3
        id: release # possibly this was missing...
        with:
          command: manifest
          token: ${{ secrets.ORG_PAT }}
          default-branch: 'main'

  publish-packages:
    runs-on: ubuntu-latest
    needs: release-please
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Dump release-please
        env:
          RELEASE_CONTEXT: ${{ toJson(needs.release-please) }}
        run: echo "$RELEASE_CONTEXT"
