on:
  push:
    branches: ['main']

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: google-github-actions/release-please-action@v3
        with:
          command: manifest
          token: ${{ secrets.GITHUB_TOKEN }}
          default-branch: 'main'

  update-format:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created == false }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - uses: actions/checkout@v3

      - uses: ./actions/npm-ci-with-cache

      - name: update format
        id: format
        run: |
          npx nx format:write --base=main
          changed_files=$(git status --porcelain --untracked-files=no | wc -l)
          echo "changed_files=${changed_files}" >> GITHUB_OUTPUT

      - name: push format changes
        if: ${{ steps.format.outputs.changed_files > 0 }}
        run: |
          echo "format:write changed files"
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
          git add -all
          git commit -m "chore(lint): apply format:write"
          git push origin

  publish-packages:
    runs-on: ubuntu-latest
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@v2
        with:
          egress-policy: audit # TODO: change to 'egress-policy: block' after couple of runs

      - run: echo "Released"
